package com.csi0n.autoreceivephone.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PHONE_ALLOW".
 */
public class PhoneAllow {

    private String phoneNumber;
    private java.util.Date time;

    public PhoneAllow() {
    }

    public PhoneAllow(String phoneNumber, java.util.Date time) {
        this.phoneNumber = phoneNumber;
        this.time = time;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

}
